### PR TITLE
Fixed after_transition with mongoid master (4.0)

### PR DESCRIPTION
**Pull request by aganov**
This problem is described in #277

### CODE REVIEW

**Comment by rafmagana** [comment]
Please, merge this!

**Comment by PavelNartov** [comment]
Really, guys - I've put this fix to config/initializers/fix_mongoid_integration.rb - and after_transtion (around_transtion too) works.

Please, merge this.

**Comment by jmuheim** [comment]
:+1:

**Comment by neckhair** [comment]
:+1:

**Comment by toothrot** [comment]
:+1:

**Comment by timstott** [comment]
:+1:

**Comment by toothrot** [comment]
We've tested this, and it works great for us.

**Comment by localredhead** [comment]
+1 please

**Comment by pedrocarrico** [comment]
:+1:

**Comment by JSFernandes** [comment]
:+1:

**Comment by sos4nt** [comment]
@obrie would you merge this, please? It's crucial for Rails 4 / Mongoid 4.

**Comment by vitalis** [comment]
:+1:

**Comment by goravbhootra** [comment]
merged couple of PRs [here](https://github.com/goravbhootra/state_machine)

**Comment by aganov** [comment]
This fork is active: https://github.com/state-machines/state_machines-mongoid

**Comment by goravbhootra** [comment]
Started merging pending PRs [here](https://github.com/goravbhootra/state_machine). Looking forward to address some issues as well.

**Pull request closed without merging**
