### PR TITLE
make sure that travis-ci status image is not cached

### PR DESCRIPTION
**Pull request by morgoth**
Without SSL url Github will cache status image url.
You can find more info at: http://about.travis-ci.org/docs/user/status-images/#using-ssl-enabled-status-images-on-github

### CODE REVIEW

**Comment by obrie** [comment]
Hey there -

I actually tried this earlier @ https://github.com/pluginaweek/state_machine/commit/781cc94ade97ce5b8fc6b332f14fe23c61f31746.  Unfortunately this doesn't render the image when using rdoc.  Perhaps there's another way to get it to render, but the only way to get that image displayed via https is to not use rdoc as far as I know.

**Comment by morgoth** [comment]
Right - I didn't checked this before pull request. Strange.
Although switching to markdown can be a good idea - Github has nice syntax highliting, such as:

``` ruby
puts 2 + 2
```

This can help in readability of state_machine examples.

I can rewrite it, if you like it.

**Comment by obrie** [comment]
That's definitely something I've been considering.  The syntax highlighting is a big plus.  If you wanna take a shot at doing the rewrite, I'd be happy to look into getting that merged.

**Comment by morgoth** [comment]
done

**Pull request closed without merging**
