### PR TITLE
fix raises when using with celluloid

### PR DESCRIPTION
**Pull request by kostya**
bug appers with 1.2, 1.1.2 was ok.

https://github.com/celluloid/celluloid/issues/206

### CODE REVIEW

**Comment by halorgium** [comment]
For anonymous classes, it will now return a `String` rather than `nil`.

**Comment by obrie** [comment]
Interesting.  Changing the behavior of `name` on Module is a little unexpected, but let me look over things.  Thanks for the heads up.

**Comment by halorgium** [comment]
@obrie in Celluloid, we only include the main `Celluloid` module and we are considering removing the `name` singleton method override. 
That change would make this change unnecessary.

**Comment by obrie** [comment]
Thanks @halorgium / @kostya!

**Pull request closed without merging**
