### PR TITLE
Prevent a common warning, accessing an undefined instance variable

### PR DESCRIPTION
**Pull request by benlangfeld**

### CODE REVIEW

**Comment by obrie** [comment]
Which runtime generates this warning?  I've never noticed it in any tests.

**Comment by benlangfeld** [comment]
CRuby 1.9.3, but only if you run ruby with `-w`. There are several others, but this is the one that occurs most in my projects which depend on state_machine.

**Comment by obrie** [comment]
Ah, I gotcha.  Thanks, I'll take a look at this sometime in the next week.

**Comment by obrie** [comment]
Hopefully should never see any warnings again from state_machine :)  Definitely file a bug if you encounter any more!

**Pull request closed without merging**
